### PR TITLE
sorry. I put it in the wrong directory

### PR DESCRIPTION
**Pull request by MinghuiZhao39**
sorry

### CODE REVIEW

**Comment by tdjames1** [comment]
@ns-rse Might be a good idea to merge this PR, which removes a stray params file.

**Comment by ns-rse** [comment]
@tdjames1 Thanks for checking, in this instance I've reset the `params` directory with #420. But useful to close this PR so the pending PRs queue is clear.

**Comment by tdjames1** [comment]
@ns-rse I saw you cleared the params directory but that didn't remove the incorrectly placed file at the root directory level that this PR would remove.

**Comment by ns-rse** [comment]
Ah, sorry for not paying attention, thank you.

**Review by ns-rse — APPROVED** [review]

**Pull request merged**
