### PR TITLE
added parameters for spp Dotticus Naggicus

### PR DESCRIPTION
**Pull request by DorottyaNagy96**

### CODE REVIEW

**Comment by DorottyaNagy96** [comment]
forgot to add a description to my pull request, but please could you merge my new added species. Thanks.

**Comment by ns-rse** [comment]
Hi @DorottyaNagy96 

I hope you're enjoying working through the Git, GitHub through GitKraken course material.

I'm afraid we only merge Pull Requests when we are delivering the material in a session and can show the review process and the impact of incorporating changes on the repository.

For that reason I'm closing the PR.

Hope you have found the material useful.

@ns-rse

**Comment by DorottyaNagy96** [comment]
Thanks Neil,

I have now realised that this is also less useful without the group.

Thanks for setting up and maintaining a great set if resources, anyway.

Have a good weekend,

Dorottya

Neil Shephard ***@***.***> ezt írta (időpont: 2024. jan. 25.,
Cs 17:00):

**Comment by ns-rse** [comment]
Hi @DorottyaNagy96 

Cool, and thanks for the compliment, but I can't take much credit for them, I use them to deliver the course and there is little maintenance involved as the main developer of them @annakrystalli did such an amazing job in the first place.

@ns-rse

**Pull request closed without merging**
