### PR TITLE
Added Ian's dino

### PR DESCRIPTION
**Pull request by kenno94-IK**
Created a new parameters file and added parameters

### CODE REVIEW

**Comment by kenno94-IK** [comment]
Hi there, could you please accept my pull request which includes an additional file with parameters for Ian's dino.

**Review by twinkarma — CHANGES_REQUESTED** [review]
Can you remove the single quote from your filename please!

**Comment by kenno94-IK** [comment]
Made changes to filename

**Review by ns-rse — APPROVED** [review]
Great thanks @kenno94-IK :+1:

**Pull request merged**
