### PR TITLE
Added Aaron's animal

### PR DESCRIPTION
**Pull request by afletcher53**
yeaaaaaaaaaah

### CODE REVIEW

**Comment by afletcher53** [comment]
yeaaaaaaaaaaaaaah

**Comment by afletcher53** [comment]
yeah

**Review by ns-rse — APPROVED** [review]
Thanks for the contribution @afletcher53 all looks good and ready to merge.

**Comment by afletcher53** [comment]
Thanks!
*Aaron Harold Andrew Fletcher *
BVetMed CertAVP MSc Artificial Intelligence MRCVS

**Pull request merged**
